[package]
name = "solvers"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
thiserror = { workspace = true }
miette = { workspace = true }
sparse    = { path = "../sparse" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
faer      = "0.16"

# ── Benchmarks ────────────────────────────────────────────────────────────────

[[bench]]
name    = "cholesky_bench"
harness = false