[package]
name = "sparse"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
thiserror = { workspace = true }
miette = { workspace = true }
num-traits = "0.2"
num-dual = { version = "0.13", optional = true }
rayon     = { version = "1.10", optional = true }
matrix-market-rs = { version = "0.1", optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
tempfile = "3"

[features]
default  = []
parallel = ["dep:rayon"]
io       = ["dep:matrix-market-rs"]
autodiff = ["dep:num-dual"]

[[bench]]
name    = "matvec"
harness = false

[[bench]]
name    = "assembly"
harness = false