[package]
name = "assembly"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
thiserror = { workspace = true }
miette = { workspace = true }
sparse    = { path = "../sparse" }
fem_core  = { path = "../fem-core" }
elements  = { path = "../elements" }
materials = { path = "../materials" }